### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by DmRos** [yousefebrahimi0/list-ai-extensions-chrome-addons-firefox#1]
<html><body>

Superpower ChatGPT | Add extra functionality to ChatGPT user interface including prompt  library, export chats, safe mode control, history, copy full chat | x | Superpower ChatGPT
-- | -- | -- | --

</body>
</html>Superpower ChatGPT 	Add extra functionality to ChatGPT user interface including prompt library, export chats, safe mode control, history, copy full chat 	x 	[Superpower ChatGPT](https://addons.mozilla.org/en-US/firefox/addon/semantic-scholar/)

should be > https://addons.mozilla.org/en-US/firefox/addon/superpower-chatgpt/

**Comment by yousefebrahimi0** [comment]
Fixed, thanks
